### ISSUE TITLE
Donate to Vibe.D Button

### ISSUE THREAD

**Issue by dallbee** [rejectedsoftware/vibed.org#33]
I've been using Vibe in personal projects for some time now, and I'd be more than willing to donate to support its development. I'm sure others would as well.

**Comment by Geod24** [comment]
There is a donation link here: http://vibed.org/get-involved#donate

**Comment by s-ludwig** [comment]
Oh right, forgot about this. I put the links there some time ago, but I think that they are more or less useless like that. They'd have to be directly on the front page so that they get at least noticed.

**Comment by dallbee** [comment]
Well, that works for now.

**Comment by s-ludwig** [comment]
@dallbee: Thanks for the donation! Much appreciated!

I'll close this ticket and leave future improvements to a pending general re-design.
