### ISSUE TITLE
Deprecated dub init example

### ISSUE THREAD

**Issue by whitebyte** [rejectedsoftware/vibed.org#35]
http://vibed.org/docs
"The easiest way to get started is to run the following command from your projects directory:"
```
$ cd /path/to/my/projects
$ dub init <project-name> vibe.d
```

I think `$ dub init <project-name> vibe.d` should be replaced with `$ dub init <project-name> --type=vibe.d`, shouldn't it?

**Comment by s-ludwig** [comment]
Thanks, that was indeed outdated.
